### ISSUE TITLE
Error when installing from source

### ISSUE THREAD

**Issue by wangtiance** [csukuangfj/kaldifeat#43]
(k2) D:\git\ASR\kaldifeat>python setup.py install
  warnings.warn(
C:\ProgramData\Anaconda3\envs\k2\lib\site-packages\setuptools\command\easy_install.py:144: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
running bdist_egg
running egg_info
writing kaldifeat.egg-info\PKG-INFO
writing dependency_links to kaldifeat.egg-info\dependency_links.txt
writing top-level names to kaldifeat.egg-info\top_level.txt
reading manifest file 'kaldifeat.egg-info\SOURCES.txt'
reading manifest template 'MANIFEST.in'
adding license file 'LICENSE'
writing manifest file 'kaldifeat.egg-info\SOURCES.txt'
installing library code to build\bdist.win-amd64\egg
running install_lib
running build_py
copying kaldifeat\python\kaldifeat\__init__.py -> build\lib.win-amd64-3.9\kaldifeat
running build_ext
Setting PYTHON_EXECUTABLE to C:\ProgramData\Anaconda3\envs\k2\python.exe
build command is:

                cmake -DCMAKE_BUILD_TYPE=Release -DPYTHON_EXECUTABLE=C:\ProgramData\Anaconda3\envs\k2\python.exe -B build\temp.win-amd64-3.9\Release -S D:\git\ASR\kaldifeat
                cmake --build build\temp.win-amd64-3.9\Release --target _kaldifeat --config Release -- -m

-- Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.19044.
-- Set BUILD_SHARED_LIBS to OFF for Windows
-- C++ Standard version: 14
-- Downloading pybind11
-- pybind11 is downloaded to D:/git/ASR/kaldifeat/build/temp.win-amd64-3.9/Release/_deps/pybind11-src
-- pybind11 v2.9.2 
-- Python executable: C:/ProgramData/Anaconda3/envs/k2/python.exe
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\ProgramData\Anaconda3\envs\k2\lib\ntpath.py", line 223, in dirname
    return split(p)[0]
  File "C:\ProgramData\Anaconda3\envs\k2\lib\ntpath.py", line 185, in split
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not NoneType
CMake Error at cmake/torch.cmake:13 (find_package):
  By not providing "FindTorch.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Torch", but
  CMake did not find one.

  Could not find a package configuration file provided by "Torch" with any of
  the following names:

    TorchConfig.cmake
    torch-config.cmake

  Add the installation prefix of "Torch" to CMAKE_PREFIX_PATH or set
  "Torch_DIR" to a directory containing one of the above files.  If "Torch"
  provides a separate development package or SDK, be sure it has been
  installed.
Call Stack (most recent call first):
  CMakeLists.txt:48 (include)

-- Configuring incomplete, errors occurred!
See also "D:/git/ASR/kaldifeat/build/temp.win-amd64-3.9/Release/CMakeFiles/CMakeOutput.log".
Traceback (most recent call last):
  File "D:\git\ASR\kaldifeat\setup.py", line 32, in <module>
    setuptools.setup(
  File "C:\ProgramData\Anaconda3\envs\k2\lib\site-packages\setuptools\__init__.py", line 87, in setup
    return distutils.core.setup(**attrs)
  File "C:\ProgramData\Anaconda3\envs\k2\lib\site-packages\setuptools\_distutils\core.py", line 148, in setup
    return run_commands(dist)
  File "C:\ProgramData\Anaconda3\envs\k2\lib\site-packages\setuptools\_distutils\core.py", line 163, in run_commands
    dist.run_commands()
  File "C:\ProgramData\Anaconda3\envs\k2\lib\site-packages\setuptools\_distutils\dist.py", line 967, in run_commands
    self.run_command(cmd)
  File "C:\ProgramData\Anaconda3\envs\k2\lib\site-packages\setuptools\dist.py", line 1214, in run_command
    super().run_command(command)
  File "C:\ProgramData\Anaconda3\envs\k2\lib\site-packages\setuptools\_distutils\dist.py", line 986, in run_command
    cmd_obj.run()
  File "C:\ProgramData\Anaconda3\envs\k2\lib\site-packages\setuptools\command\install.py", line 74, in run
    self.do_egg_install()
  File "C:\ProgramData\Anaconda3\envs\k2\lib\site-packages\setuptools\command\install.py", line 123, in do_egg_install
    self.run_command('bdist_egg')
  File "C:\ProgramData\Anaconda3\envs\k2\lib\site-packages\setuptools\_distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:\ProgramData\Anaconda3\envs\k2\lib\site-packages\setuptools\dist.py", line 1214, in run_command
    super().run_command(command)
  File "C:\ProgramData\Anaconda3\envs\k2\lib\site-packages\setuptools\_distutils\dist.py", line 986, in run_command
    cmd_obj.run()
  File "C:\ProgramData\Anaconda3\envs\k2\lib\site-packages\setuptools\command\bdist_egg.py", line 165, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "C:\ProgramData\Anaconda3\envs\k2\lib\site-packages\setuptools\command\bdist_egg.py", line 151, in call_command
    self.run_command(cmdname)
  File "C:\ProgramData\Anaconda3\envs\k2\lib\site-packages\setuptools\_distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:\ProgramData\Anaconda3\envs\k2\lib\site-packages\setuptools\dist.py", line 1214, in run_command
    super().run_command(command)
  File "C:\ProgramData\Anaconda3\envs\k2\lib\site-packages\setuptools\_distutils\dist.py", line 986, in run_command
    cmd_obj.run()
  File "C:\ProgramData\Anaconda3\envs\k2\lib\site-packages\setuptools\command\install_lib.py", line 11, in run
    self.build()
  File "C:\ProgramData\Anaconda3\envs\k2\lib\site-packages\setuptools\_distutils\command\install_lib.py", line 107, in build   
    self.run_command('build_ext')
  File "C:\ProgramData\Anaconda3\envs\k2\lib\site-packages\setuptools\_distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:\ProgramData\Anaconda3\envs\k2\lib\site-packages\setuptools\dist.py", line 1214, in run_command
    super().run_command(command)
  File "C:\ProgramData\Anaconda3\envs\k2\lib\site-packages\setuptools\_distutils\dist.py", line 986, in run_command
    cmd_obj.run()
  File "C:\ProgramData\Anaconda3\envs\k2\lib\site-packages\setuptools\command\build_ext.py", line 79, in run
    _build_ext.run(self)
  File "C:\ProgramData\Anaconda3\envs\k2\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 339, in run       
    self.build_extensions()
  File "C:\ProgramData\Anaconda3\envs\k2\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 448, in build_extensions
    self._build_extensions_serial()
  File "C:\ProgramData\Anaconda3\envs\k2\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 473, in _build_extensions_serial
    self.build_extension(ext)
  File "D:\git\ASR\kaldifeat\cmake\cmake_extension.py", line 84, in build_extension
    raise Exception("Failed to build kaldifeat")
Exception: Failed to build kaldifeat

**Comment by wangtiance** [comment]
And here is my conda environment:

# packages in environment at C:\ProgramData\Anaconda3\envs\k2:
#
# Name                    Version                   Build  Channel
blas                      1.0                         mkl    defaults
ca-certificates           2022.4.26            haa95532_0    defaults
certifi                   2022.6.15        py39haa95532_0    defaults
intel-openmp              2021.4.0          haa95532_3556    defaults
k2                        1.17.dev20220710+cpu.torch1.12.0          pypi_0    pypi
mkl                       2021.4.0           haa95532_640    defaults
mkl-service               2.4.0            py39h2bbff1b_0    defaults
mkl_fft                   1.3.1            py39h277e83a_0    defaults
mkl_random                1.2.2            py39hf11a4ad_0    defaults
numpy                     1.22.3           py39h7a0a035_0    defaults
numpy-base                1.22.3           py39hca35cd5_0    defaults
openssl                   1.1.1q               h2bbff1b_0    defaults
pip                       22.1.2           py39haa95532_0    defaults
python                    3.9.12               h6244533_0    defaults
python-graphviz           0.20                     pypi_0    pypi
python_abi                3.9                      2_cp39    conda-forge
sentencepiece             0.1.96           py39h2e07f2f_1    conda-forge
setuptools                61.2.0           py39haa95532_0    defaults
six                       1.16.0             pyhd3eb1b0_1    defaults
sqlite                    3.38.5               h2bbff1b_0    defaults
torch                     1.12.0                   pypi_0    pypi
torchaudio                0.12.0                   pypi_0    pypi
typing-extensions         4.3.0                    pypi_0    pypi
tzdata                    2022a                hda174b7_0    defaults
vc                        14.2                 h21ff451_1    defaults
vs2015_runtime            14.27.29016          h5e58377_2    defaults
wheel                     0.37.1             pyhd3eb1b0_0    defaults
wincertstore              0.2              py39haa95532_2    defaults

(k2) D:\git\ASR\kaldifeat>

**Comment by wangtiance** [comment]
The problem was with my torch. Worked after re-installing.
